Add database
Soylf/java-filmorate pull request #10
Opened 2023-12-16 14:04 UTC by Soylf

2023-12-16 14:30 UTC, Soylf commented
dto пока не как не используется, но сделал их в упор на будущее

2023-12-17 00:56 UTC, Soylf commented
и пока поле друзей не убрал в пользователях, хоть и знаю что храним его как и многие данные в бд, просто так легче иногда  воспринимать информацию

2023-12-17 08:24 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
> +package ru.yandex.practicum.filmorate.Ui;
пакеты с большой буквы не называют

2023-12-17 08:30 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
>      }
Возвращать  ResponseEntity<Object> или Object не есть хорошая практика, т.к.  "безликие" базовые типы. Нужно вернуть ApiError, который как раз будет отражать суть происходящего. А для статуса воспользоваться аннотацией.

2023-12-17 08:32 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
>          List<String> errors = ex.getBindingResult().getFieldErrors().stream().map(DefaultMessageSourceResolvable::getDefaultMessage).collect(Collectors.toList());
Раз здесь получаешь полный список ошибок, то почему только в этом методе. В остальных тоже полезно такой список иметь.

2023-12-17 08:35 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film addFilm(@RequestBody Film film) {
Dto сделаны, а здесь не используются?

2023-12-17 08:38 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film updateFilm(@RequestBody Film film) {
Как насчет освоить валидацию с помощью аннотаций (@Valid, @Validated) и начать использовать?

2023-12-17 08:39 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public List<Genre> getGenreById() {
Название метода не соответствует сути

2023-12-17 08:41 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Components/Genre.java
> +package ru.yandex.practicum.filmorate.model.Components;
Components?

2023-12-17 08:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private Set<Integer> like = new HashSet<>();
Поля с лайуами не должно быть в фильме

2023-12-17 08:43 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Поля с друзьями не должно быть в пользователе

2023-12-17 08:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +            for (Genre genre : film.getGenres()) {
В цикле делать вставку по одной записи медленно. Нужно воспользоваться пакетной вставкой batchUpdate
https://habr.com/ru/articles/703828/

2023-12-17 08:48 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +        for (Genre genre : film.getGenres()) {
Пакетная вставка

2023-12-17 08:50 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +                rs.getInt("duration")
А mpa?

2023-12-17 08:52 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/service/FilmService.java
> +    private static void checkBody(Film film) throws ValidationException {
Почему body?

2023-12-17 08:53 UTC, VadimZharkov requested changes
Нужно исправить замечания

2023-12-17 10:26 UTC, Soylf commented
вроде все, некоторые темы реализую потом :3

2023-12-18 05:21 UTC, Soylf commented
Замечания исправленны

2023-12-18 07:10 UTC, VadimZharkov reviewed
Основным средством сборки является мавен. В идею импортируем проект из pom.
Поэтому папку с .idea пушить не нужно

2023-12-18 07:17 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +            film.setMpa(mpaStorage.getMpaById(rs.getInt("mpa_id")).get());
mpaStorage.getMpaById - это доп запрос к базе. Нужно стараться избезать доп запросов.
Если в SELECT * FROM Film добавить джоин к Mpa, то можно и фильм и мпа вытянуть одним запросом

2023-12-18 07:19 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +        }
Повторюсь, а здесь почему нет пакетной вставки?

2023-12-18 07:24 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/ui/RestExceptionHandler.java
> +
Замечания не исправлены.
Плюс как название пакета ui коррелирует с обработкой эксепшенов? Это как назвать коробку с фломастерами - карандаши.

2023-12-18 07:25 UTC, VadimZharkov requested changes
Не все исправлено.

2023-12-18 07:39 UTC, Soylf commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +            film.setMpa(mpaStorage.getMpaById(rs.getInt("mpa_id")).get());
понял

2023-12-18 07:56 UTC, Soylf commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/film/FilmDbStorage.java
> +            film.setMpa(mpaStorage.getMpaById(rs.getInt("mpa_id")).get());
принципи думаю id хватет, ибо есть контролеры которые выводят их

2023-12-18 12:32 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/storage/impl/InMemoryFilmStorage.java
InMemory реализации удаляем, они больше не нужны

2023-12-18 12:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/storage/daoImpl/FilmDaoStorageImpl.java
> +        String sqlQuery = "SELECT film_id, film_name, description, release_date, duration, rate, mpa_id FROM Film";
JOIN c Mpa не увидел
если бы он был то результат запроса пришло бы еще два атрибута Mpa.mpa_id и Mpa.name и маппер можно было так реализовать
```
	static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
		return new Film(
				rs.getLong("film_id"),
				rs.getString("FILMS.name"),
				rs.getString("description"),
				toLocalDate(rs.getDate("release_date")),
				rs.getLong("duration"),
				rs.getLong("rate"),
				new Mpa(rs.getLong("Mpa.mpa_id"), rs.getString("Mpa.name")));
	}
```
Обрати внимание на последнюю строчку
Mpa создается конструктором а не обращением к БД посредством Dao

2023-12-18 12:43 UTC, VadimZharkov requested changes
Нужно добиться прохождения тестов

2023-12-19 22:06 UTC, Soylf commented
Пощадите ^_^

2023-12-20 07:31 UTC, VadimZharkov approved these changes

2023-12-20 23:46 UTC, merged