new
Soylf/java-filmorate pull request #9
Opened 2023-11-18 20:26 UTC by Soylf

2023-11-22 09:53 UTC, Soylf commented
Вопрос, правильно ли сделал что все равно разветвил логику на 2 класс с бизнес логикой или стоило все в 1?

2023-11-22 15:09 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
> +package ru.yandex.practicum.filmorate.Ui;
Ui - пакеты именовать с большой буквы запрещено

2023-11-22 15:10 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
> +@ControllerAdvice("ru.yandex.practicum.filmorate")
нужно использовать @RestControllerAdvice

2023-11-22 15:12 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/Ui/RestExceptionHandler.java
> +
Нужно добавить обработку Throwable в 500 статус

2023-11-22 15:17 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new ValidationException("Такого фильма нету.");
Если что-то не найдено, то это не ошибка валидации. Лучше отдельное исключение сделать FilmNotFound или общее для всех видов сущностей DataNotFound

2023-11-22 15:22 UTC, VadimZharkov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Пустой класс с тестами нужно убрать из проекта

2023-11-22 15:25 UTC, VadimZharkov requested changes
Можно улучшить и нужно исправить замечания.

2023-11-22 15:27 UTC, VadimZharkov commented
> Вопрос, правильно ли сделал что все равно разветвил логику на 2 класс с бизнес логикой или стоило все в 1? И еще надо было делать для классов сервера свои интерфейсы или лучше как я сделал?

То что развитвил правильно, другое дело что они похожи и можно выделить общую часть в базовый класс-дженерик.
Да, для классов-сервисов принято делать интерфейсы, но в данном ТЗ этого явно не требуют.

2023-11-23 06:44 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("addFilm_запушен");
Добавь логирование для остальных методов тоже (требование ТЗ)

2023-11-23 06:47 UTC, VadimZharkov requested changes
Нужно добавить логирование для методов котроллеров

2023-11-24 05:56 UTC, VadimZharkov approved these changes

2023-11-24 09:20 UTC, merged